name: alert_lah
description: This is Fork of firebase_messaging version 7.0.1. A Flutter plugin for Firebase Cloud Messaging, a cross-platform
  messaging solution that lets you reliably deliver messages on Android and iOS.
homepage: https://github.com/Undiscovereds/alert-lah
version: 1.0.1

flutter:
  plugin:
    platforms:
      android:
        package: io.flutter.plugins.firebasemessaging
        pluginClass: FirebaseMessagingPlugin
      ios:
        pluginClass: FLTFirebaseMessagingPlugin

dependencies:
  meta: ^1.3.0
  platform: ^3.0.0
  flutter:
    sdk: flutter
  firebase_core: ^1.3.0

environment:
  sdk: ">=2.0.0 <3.0.0"
  flutter: ">=1.12.13+hotfix.5 <3.0.0"
